name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    uses: Deroino/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      # Single platform build for AMD64 only
      platforms: linux/amd64
      
      # Push to GHCR only
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/deroino/ultroid
      
      # Enable email notifications
      email-enable: true
      email-to: wangchenghow@foxmail.com
      email-server: smtp.qq.com
      email-port: 465
      
      # Enable push notifications
      push-notify-enable: true
      push-notify-url: https://reminderapi.joyslinktech.com/v1/push/key/PSH1747376891203bCK3tG1pKvx5yAHo
      
    secrets:
      # Docker Hub credentials
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKER_PASSWORD }}
      
      # Email credentials
      email-username: ${{ secrets.EMAIL_USERNAME }}
      email-password: ${{ secrets.EMAIL_PASSWORD }}